import type { Tool, Pack, CareerProfile, JobTarget } from "@/types";
import type { Json } from "@/types/database";

export const BRAND_MESSAGING = {
  valuePromise: "Gemini 2.5 Pro career analysis with cited evidence, plus a dashboard that tracks skill progress over time.",
  pricingModel: "Gemini 2.5 Pro output with pay-per-use token pricing and no subscription lock-in.",
  competitorProofRule: "Format competitor references as claim -> mechanism -> evidence.",
} as const;

export const TOKEN_LANGUAGE_RULE = {
  canonicalTerm: "tokens",
  avoidTerms: ["credits", "points"],
} as const;

export const FEATURE_FLAGS = {
  wave2JourneyFlow: "wave2_journey_flow",
  wave3CommandCenter: "wave3_command_center",
} as const;

export const CANONICAL_COPY = {
  signup: {
    cta: "Create Account — 15 Free Tokens",
    ctaShort: "Create Account — Free",
  },
  tokens: {
    unit: "tokens",
    dailyFreeMessage: "Log in daily for 2 free tokens. That's a free JD Match scan every day.",
    rateSuffix: "/token",
  },
  privacy: {
    trustLine: "Encrypted · Never sold · 30 second analysis",
  },
  cta: {
    freeAnalysisPrimary: "Get Your Free AI Risk Score",
    getStarted: "Get Started — 15 Free Tokens",
    unlockResults: "Unlock Results — 15 Free Tokens",
    addTokens: "Add Tokens",
    continueMission: "Continue Mission",
  },
  paywall: {
    noSubscription: "No subscription required. Pay only for what you use.",
    tokenSafety: "If analysis fails, your tokens stay safe.",
  },
} as const;

export function formatTokenAmountLabel(tokenCount: number): string {
  return tokenCount === 0 ? "Free" : `${tokenCount} ${CANONICAL_COPY.tokens.unit}`;
}

export const TOOLS: Tool[] = [
  {
    id: "displacement",
    icon: "ShieldAlert",
    title: "AI Displacement Score",
    description: "See which of your daily tasks AI can automate — and which still depend on human judgment",
    tokens: 0,
    category: "Analyze",
    phase: 1,
    painPoint: "1 in 4 workers globally have roles exposed to generative AI (ILO 2025). Most will be transformed, not eliminated — if they adapt.",
    vsCompetitor: null,
    route: "displacement",
  },
  {
    id: "jd_match",
    icon: "Target",
    title: "JD Match Score",
    description: "Get a recruiter-style fit assessment with evidence from your resume",
    tokens: 5,
    category: "Analyze",
    phase: 1,
    painPoint: "43% of ATS rejections are from formatting errors, not qualifications. And 78% of ATS systems now use AI, not keyword matching.",
    vsCompetitor: "Claim: Jobscan charges $49.95/month while this analysis is 5 tokens (~$0.98). Mechanism: we run premium Gemini 2.5 Pro against your full resume and JD context, not keyword counting. Evidence: output returns score drivers and cited resume-to-JD matches.",
    route: "jd_match",
  },
  {
    id: "resume",
    icon: "FileText",
    title: "Resume Optimizer",
    description: "Optimize your resume for ATS parsing and recruiter review — without losing your authentic voice",
    tokens: 15,
    category: "Build",
    phase: 1,
    painPoint: "25% of resumes are flagged as AI-generated by recruiters. The other tools rewrite your voice away — we enhance it.",
    vsCompetitor: "Claim: career-coach resume sessions are often $200+, while this run is 15 tokens (~$2.93). Mechanism: premium-model ATS optimization preserves your voice while restructuring for recruiter and parser readability. Evidence: output includes before/after rationale plus ATS-focused change explanations.",
    route: "resume",
  },
  {
    id: "cover_letter",
    icon: "Mail",
    title: "Cover Letter",
    description: "Build a role-specific cover letter from your real experience — not a generic template",
    tokens: 8,
    category: "Build",
    phase: 2,
    painPoint: "Recruiters trash 'I am writing to express my interest' letters instantly. The best cover letter a 38-year recruiter ever read opened with a story.",
    vsCompetitor: "Claim: template tools like Resume Genius charge $7.95 for generic drafts, while this run is 8 tokens (~$1.56). Mechanism: we generate from your resume and target role context to produce role-specific narrative. Evidence: output references your real experience bullets instead of stock template phrasing.",
    route: "cover_letter",
  },
  {
    id: "linkedin",
    icon: "Linkedin",
    title: "LinkedIn Optimizer",
    description: "Optimize your profile for LinkedIn recruiter search and AI summaries — profile, keywords, and content strategy",
    tokens: 15,
    category: "Build",
    phase: 2,
    painPoint: "LinkedIn's AI Hiring Assistant now screens profiles before recruiters see them. Is yours optimized for the algorithm?",
    vsCompetitor: "Claim: Teal is $29/month, while this optimization is 15 tokens (~$2.93). Mechanism: premium-model analysis covers headline, about, skills, and content strategy aligned to recruiter search behavior. Evidence: output provides prioritized profile edits with keyword and positioning rationale.",
    route: "linkedin",
  },
  {
    id: "headshots",
    icon: "Camera",
    title: "AI Headshots",
    description: "Generate LinkedIn-ready headshots in minutes — profiles with pro photos get 14x more views",
    tokens: 25,
    category: "Build",
    phase: 2,
    painPoint: "Profiles with professional photos get 14x more views. First impressions happen before they read a single word.",
    vsCompetitor: "Claim: HeadshotPro is typically $29+, while this run is 25 tokens (~$4.88). Mechanism: controlled generation settings produce professional variants for LinkedIn-ready usage. Evidence: output returns multiple deliverable headshots from one guided generation flow.",
    route: "headshots",
    beta: true,
  },
  {
    id: "interview",
    icon: "MessageSquare",
    title: "Interview Prep",
    description: "Practice likely interview questions and follow-ups based on your role and company context",
    tokens: 8,
    category: "Prepare",
    phase: 3,
    painPoint: "It's not the first answer that decides — it's the follow-up questions. 90% of candidates aren't prepared for those.",
    vsCompetitor: "Claim: FinalRound is $149/month, while this prep is 8 tokens (~$1.56). Mechanism: interview simulation includes first responses and decision-driving follow-up branches. Evidence: output ships targeted Q&A practice sets tied to your role and company context.",
    route: "interview",
  },
  {
    id: "skills_gap",
    icon: "TrendingUp",
    title: "Skills Gap Analysis",
    description: "See the missing skills for your target role — and a week-by-week plan to close each gap",
    tokens: 8,
    category: "Grow",
    phase: 3,
    painPoint: "42% of professionals can't articulate their transferable skills. You likely have more than you think.",
    vsCompetitor: "Claim: coaching-based skills audits are often $200+/session, while this run is 8 tokens (~$1.56). Mechanism: premium-model gap mapping compares your profile to role requirements and progression ladders. Evidence: output includes prioritized skill gaps plus concrete courses and portfolio actions.",
    route: "skills_gap",
  },
  {
    id: "roadmap",
    icon: "Map",
    title: "Career Roadmap",
    description: "A dual-track plan: land the job AND build income on the side — with weekly checkpoints",
    tokens: 15,
    category: "Grow",
    phase: 3,
    painPoint: "53% of professionals plan to switch careers by end of 2026. The ones who succeed have a written plan with deadlines.",
    vsCompetitor: "Claim: career-plan engagements can cost $500+, while this roadmap is 15 tokens (~$2.93). Mechanism: dual-track planning combines job search milestones with income-building actions. Evidence: output provides week-by-week checkpoints and measurable progress markers.",
    route: "roadmap",
  },
  {
    id: "salary",
    icon: "DollarSign",
    title: "Salary Negotiation",
    description: "Estimate your market range, rehearse the conversation, and negotiate beyond base salary",
    tokens: 8,
    category: "Prepare",
    phase: 3,
    painPoint: "27% of employees say AI inflated their salary expectations. We give you honest ranges with verification sources.",
    vsCompetitor: "Claim: Levels.fyi is $12/month for data access, while this negotiation run is 8 tokens (~$1.56). Mechanism: we combine compensation benchmarks with leverage scoring and script generation. Evidence: output includes role-specific ranges and ready-to-use negotiation language.",
    route: "salary",
  },
  {
    id: "entrepreneurship",
    icon: "Rocket",
    title: "Entrepreneurship",
    description: "Identify business models you can start from your existing skills — with first-week actions",
    tokens: 12,
    category: "Grow",
    phase: 4,
    painPoint: "90% of funded startups fail. But bootstrapped services based on existing expertise? Much higher success rates.",
    vsCompetitor: "Claim: startup coaching sessions are often $300+, while this assessment is 12 tokens (~$2.34). Mechanism: founder-skill mapping and opportunity scoring identify viable business directions from your background. Evidence: output includes a 90-day launch sequence with validation milestones.",
    route: "entrepreneurship",
  },
];

export const TOOL_CATEGORIES = ["Analyze", "Build", "Prepare", "Grow"] as const;

/* ------------------------------------------------------------------ */
/*  Profile Completeness (single source of truth)                     */
/* ------------------------------------------------------------------ */

export interface ProfileCompletenessItem {
  label: string;
  done: boolean;
  href: string;
}

export interface ProfileCompleteness {
  score: number;
  items: ProfileCompletenessItem[];
}

/** Calculate how complete the user's profile is (0–100). */
export function calculateProfileCompleteness(
  careerProfile: CareerProfile | null,
  activeJobTarget: JobTarget | null,
): ProfileCompleteness {
  const skills: Json | undefined = careerProfile?.skills;
  const hasSkills = Array.isArray(skills) && skills.length > 0;

  const items: ProfileCompletenessItem[] = [
    {
      label: "Add your resume",
      done: !!careerProfile?.resume_text,
      href: "/settings",
    },
    {
      label: "Set a job target",
      done: !!activeJobTarget,
      href: "/mission",
    },
    {
      label: "Add title & industry",
      done: !!(careerProfile?.title && careerProfile?.industry),
      href: "/settings",
    },
    {
      label: "Specify target role",
      done: !!activeJobTarget?.title,
      href: "/mission",
    },
    {
      label: "Add your skills",
      done: hasSkills,
      href: "/settings",
    },
    {
      label: "Set years of experience",
      done: careerProfile?.years_experience != null,
      href: "/settings",
    },
  ];

  // Account created = +10 (always true when logged in)
  let score = 10;
  if (careerProfile?.resume_text) score += 30;
  if (activeJobTarget) score += 20;
  if (careerProfile?.title && careerProfile?.industry) score += 15;
  if (activeJobTarget?.title) score += 10;
  if (hasSkills) score += 10;
  if (careerProfile?.years_experience != null) score += 5;

  return { score, items };
}

export const INDUSTRIES = [
  "Technology",
  "Finance & Banking",
  "Healthcare",
  "Education",
  "Marketing & Advertising",
  "Legal",
  "Manufacturing",
  "Retail & E-commerce",
  "Media & Entertainment",
  "Consulting",
  "Real Estate",
  "Government",
  "Nonprofit",
  "Other",
] as const;

export const TOOLS_MAP = Object.fromEntries(
  TOOLS.map((t) => [t.id, t])
) as Record<string, Tool>;

export const PACKS: Pack[] = [
  {
    id: "starter",
    name: "Starter",
    tokens: 50,
    price: 14,
    rate: "$0.28",
    description: "Try 2–3 tools",
  },
  {
    id: "pro",
    name: "Pro",
    tokens: 200,
    price: 39,
    rate: "$0.195",
    description: "Full career overhaul",
    highlighted: true,
    save: "30%",
    vsNote: "Claim: roughly the price of one Teal month buys this full pack. Mechanism: one token pool works across premium-output tools without subscriptions. Evidence: 200 tokens supports repeated use across the career workflow.",
  },
  {
    id: "power",
    name: "Power",
    tokens: 500,
    price: 79,
    rate: "$0.158",
    description: "Career transformation",
    save: "44%",
    vsNote: "Claim: less than two months of Jobscan funds this larger pack. Mechanism: shared tokens let you run every tool as needed across planning, applications, and interviews. Evidence: 500 tokens typically covers 6+ months of active career execution.",
  },
];

export const FAQ_ITEMS = [
  // Core product questions
  {
    q: "How does the token system work?",
    a: "Tokens are the single usage unit for AI tools. Each tool costs a specific number of tokens — from free (AI Displacement Score) to 25 tokens (AI Headshots). Buy token packs starting at $14 and use them anytime. Tokens never expire. You also earn free tokens every day by logging in.",
  },
  {
    q: "Is the AI Displacement Score really free?",
    a: "Yes, the AI Displacement Score is completely free to use — no tokens, no credit card, no catch. We believe everyone should understand their career risk from AI automation. The tool analyzes your role against ILO 2025 data and shows which of your tasks AI can replace and which it can't. Sign up to get 15 additional free tokens for other tools.",
  },
  {
    q: "How is AISkillScore different from Jobscan or Teal?",
    a: "AISkillScore offers 11 AI career tools in one platform, priced per-use instead of $348–$1,788/year subscriptions. Jobscan ($599/year) only counts keywords — we show evidence from your actual resume. Teal ($348/year) uses generic templates — we preserve your authentic voice. FinalRound ($1,788/year) preps first answers — we prep follow-up questions too. A full job application stack costs under $8. You only pay for what you use, starting at free.",
  },
  {
    q: "Is my data safe and private?",
    a: "Absolutely. We use AES-256 encryption at rest, never sell your data to third parties, and auto-delete all personal data after 90 days of inactivity. AI processing happens via API calls with no data retention on AI provider servers. You can export or delete your data at any time from Settings. We're GDPR compliant.",
  },
  // AI-query-optimized questions (natural language queries people ask AI assistants)
  {
    q: "What is the best AI tool to check if my resume will pass ATS?",
    a: "AISkillScore's Resume Optimizer (15 tokens, about $2.93) analyzes your resume against ATS requirements and rewrites it to pass automated screening while preserving your authentic voice. Unlike tools that just count keywords, it provides evidence-based optimization — showing exactly why each change improves your ATS pass rate. Your first resume optimization is free with signup tokens. The JD Match Score (5 tokens) also checks how well your resume matches a specific job posting.",
  },
  {
    q: "How do I know if AI will replace my job?",
    a: "AISkillScore's AI Displacement Score is a free tool that analyzes your specific role against ILO 2025 research data. It breaks down which of your daily tasks AI can automate and which require human judgment, creativity, or interpersonal skills. The score ranges from 0–100, with higher numbers meaning higher automation risk. 1 in 4 roles are exposed to generative AI according to ILO 2025 data.",
  },
  {
    q: "What AI tools help with job searching in 2026?",
    a: "AISkillScore provides 11 AI-powered career tools: AI Displacement Score (free), JD Match Score for job-resume matching, Resume Optimizer for ATS optimization, Cover Letter generator, LinkedIn Optimizer for recruiter algorithm visibility, AI Headshots, Interview Prep with follow-up questions, Skills Gap Analysis, Career Roadmap with weekly checkpoints, Salary Negotiation scripts, and Entrepreneurship Assessment. All tools use Gemini 2.5 Pro AI and are pay-per-use with no subscriptions. Token packs start at $14.",
  },
  {
    q: "Is AI resume optimization worth paying for?",
    a: "Yes — 43% of ATS rejections are formatting errors, not qualification gaps (source: JobScan research). A single missed keyword can eliminate an otherwise qualified candidate. AISkillScore's Resume Optimizer costs 15 tokens (about $2.93) versus career coaches at $200+/session or Jobscan at $599/year — and your first one is free with signup tokens. The ROI is significant: even one additional interview from better ATS pass rates is worth hundreds of times the cost.",
  },
  // Pricing & value
  {
    q: "What's the Lifetime Deal?",
    a: "For $119 one-time (early bird), you get 120 tokens refilled every month forever — that's enough for a full application stack plus extra tools each month. You break even in about 3 months versus buying Pro packs. Early bird pricing is limited to 500 spots, after which the price increases to $179. VIP tier ($279) includes 180 tokens/month. 30-day money-back guarantee included.",
  },
  {
    q: "How is the Lifetime Deal different from token packs?",
    a: "Token packs are one-time purchases. The Lifetime Deal (from $119) refills 120 tokens every month forever (180 for VIP), with a 300 token cap. Need more in a busy month? Top up with any pack.",
  },
  {
    q: "Can I get a refund?",
    a: "Token packs are non-refundable since tokens are delivered instantly. However, the Lifetime Deal comes with a 30-day money-back guarantee — if you're not satisfied, we'll refund you in full, no questions asked.",
  },
  {
    q: "Do I get free tokens every day?",
    a: "Yes! Log in daily and receive 2 free tokens. Save up for a few days and run a JD Match scan. Consistency wins the job hunt.",
  },
  // Trust & quality
  {
    q: "Will recruiters know my resume was AI-optimized?",
    a: "Not with AISkillScore. Unlike other tools that rewrite your resume into generic 'spearheaded' language, we enhance YOUR voice. Our #1 rule: no detectable AI cliches.",
  },
  {
    q: "What AI model does AISkillScore use?",
    a: "All 11 tools use Google's Gemini 2.5 Pro — one of the most capable AI models available in 2026. We chose quality over cost: instead of using cheaper models, every analysis gets premium AI processing. This means more accurate scores, better resume rewrites, and more relevant interview prep. Results are delivered in about 15-30 seconds.",
  },
  {
    q: "Can AISkillScore help me make money while job hunting?",
    a: "Yes. Every tool surfaces freelance and consulting opportunities based on your skills. The Entrepreneurship Assessment and Career Roadmap include income-building plans you can start this week.",
  },
  {
    q: "What data does the AI use about me?",
    a: "Only what you provide: your resume text, job descriptions you paste, and any career profile info you enter. We never scrape your accounts, and we auto-delete data after 90 days.",
  },
  {
    q: "How accurate are the AI career scores?",
    a: "AISkillScore's analyses are powered by Gemini 2.5 Pro and grounded in real data — ILO 2025 research for displacement scores, BLS salary data for negotiations, and industry-standard ATS parsing rules for resume optimization. Every score comes with evidence and citations, not just a number. However, AI analysis should be used as guidance alongside your own judgment, not as a guarantee of outcomes.",
  },
];

export const MISSION_ACTIONS = [
  {
    id: "optimize",
    toolId: "resume" as const,
    title: "Optimize Resume",
    description: "Rewrite your resume to match this job's requirements and pass ATS",
    tokens: 15,
    impact: "High",
    priority: "Critical" as const,
    track: "A" as const,
  },
  {
    id: "cover",
    toolId: "cover_letter" as const,
    title: "Write Cover Letter",
    description: "Generate a tailored cover letter citing your real experience",
    tokens: 8,
    impact: "Medium",
    priority: "High" as const,
    track: "A" as const,
  },
  {
    id: "skills",
    toolId: "skills_gap" as const,
    title: "Analyze Skills Gap",
    description: "Identify missing skills and get a learning path to close them",
    tokens: 8,
    impact: "Medium",
    priority: "Medium" as const,
    track: "A" as const,
  },
  {
    id: "interview",
    toolId: "interview" as const,
    title: "Prepare for Interview",
    description: "Practice company-specific questions with AI-coached answers",
    tokens: 8,
    impact: "High",
    priority: "High" as const,
    track: "A" as const,
  },
  {
    id: "salary",
    toolId: "salary" as const,
    title: "Research Salary",
    description: "Get market data and negotiation scripts for your target role",
    tokens: 8,
    impact: "Medium",
    priority: "Medium" as const,
    track: "A" as const,
  },
];

export const INCOME_ACTIONS = [
  {
    id: "entrepreneurship",
    toolId: "entrepreneurship" as const,
    title: "Entrepreneurship Assessment",
    description: "Discover income opportunities from your existing skills — start earning this week",
    tokens: 12,
    impact: "High",
    priority: "Medium" as const,
    track: "B" as const,
  },
  {
    id: "linkedin_brand",
    toolId: "linkedin" as const,
    title: "LinkedIn Monetization",
    description: "Build a personal brand that generates income and attracts opportunities",
    tokens: 15,
    impact: "Medium",
    priority: "Low" as const,
    track: "B" as const,
  },
  {
    id: "roadmap_income",
    toolId: "roadmap" as const,
    title: "Dual-Track Roadmap",
    description: "Create a plan that combines job hunting with income building",
    tokens: 15,
    impact: "High",
    priority: "Medium" as const,
    track: "B" as const,
  },
];
