import type { Tool, Pack, CareerProfile, JobTarget } from "@/types";
import type { Json } from "@/types/database";

export const TOOLS: Tool[] = [
  {
    id: "displacement",
    icon: "ShieldAlert",
    title: "AI Displacement Score",
    description: "Find out which of your daily tasks AI threatens — and which make you irreplaceable",
    tokens: 0,
    category: "Analyze",
    phase: 1,
    painPoint: "1 in 4 workers globally have roles exposed to generative AI (ILO 2025). Most will be transformed, not eliminated — if they adapt.",
    vsCompetitor: null,
    route: "displacement",
  },
  {
    id: "jd_match",
    icon: "Target",
    title: "JD Match Score",
    description: "Get a recruiter's honest verdict on your fit — with evidence from your resume",
    tokens: 5,
    category: "Analyze",
    phase: 1,
    painPoint: "43% of ATS rejections are from formatting errors, not qualifications. And 78% of ATS systems now use AI, not keyword matching.",
    vsCompetitor: "Jobscan charges $49.95/month to count keywords. We use Gemini 2.5 Pro to analyze your actual resume — for $0.98.",
    route: "jd_match",
  },
  {
    id: "resume",
    icon: "FileText",
    title: "Resume Optimizer",
    description: "Optimize your resume for ATS and recruiters — without losing your authentic voice",
    tokens: 15,
    category: "Build",
    phase: 1,
    painPoint: "25% of resumes are flagged as AI-generated by recruiters. The other tools rewrite your voice away — we enhance it.",
    vsCompetitor: "Career coaches charge $200+ per session. Same ATS optimization for $2.93. Your first one is free.",
    route: "resume",
  },
  {
    id: "cover_letter",
    icon: "Mail",
    title: "Cover Letter",
    description: "A cover letter that tells your story — not a template that sounds like everyone else",
    tokens: 8,
    category: "Build",
    phase: 2,
    painPoint: "Recruiters trash 'I am writing to express my interest' letters instantly. The best cover letter a 38-year recruiter ever read opened with a story.",
    vsCompetitor: "Resume Genius charges $7.95 for a fill-in-the-blank template. We write a custom story from your resume — $1.56.",
    route: "cover_letter",
  },
  {
    id: "linkedin",
    icon: "Linkedin",
    title: "LinkedIn Optimizer",
    description: "Make LinkedIn's AI recommend you to recruiters — profile, keywords, and content strategy",
    tokens: 15,
    category: "Build",
    phase: 2,
    painPoint: "LinkedIn's AI Hiring Assistant now screens profiles before recruiters see them. Is yours optimized for the algorithm?",
    vsCompetitor: "Teal charges $29/mo. We optimize for LinkedIn's 2026 AI Hiring Assistant — profile, content, and brand strategy — for $2.93.",
    route: "linkedin",
  },
  {
    id: "headshots",
    icon: "Camera",
    title: "AI Headshots",
    description: "Professional headshots in minutes — profiles with pro photos get 14x more views",
    tokens: 25,
    category: "Build",
    phase: 2,
    painPoint: "Profiles with professional photos get 14x more views. First impressions happen before they read a single word.",
    vsCompetitor: "HeadshotPro charges $29+. We charge 25 tokens (~$4.88). Same AI, fraction of the price.",
    route: "headshots",
    beta: true,
  },
  {
    id: "interview",
    icon: "MessageSquare",
    title: "Interview Prep",
    description: "Practice the exact questions they'll ask — including the follow-ups that decide who gets the offer",
    tokens: 8,
    category: "Prepare",
    phase: 3,
    painPoint: "It's not the first answer that decides — it's the follow-up questions. 90% of candidates aren't prepared for those.",
    vsCompetitor: "FinalRound costs $149/mo and preps your first answer. We prep the follow-up questions that actually decide outcomes — $1.56.",
    route: "interview",
  },
  {
    id: "skills_gap",
    icon: "TrendingUp",
    title: "Skills Gap Analysis",
    description: "See what's actually missing for your target role — and a week-by-week plan to close each gap",
    tokens: 8,
    category: "Grow",
    phase: 3,
    painPoint: "42% of professionals can't articulate their transferable skills. You likely have more than you think.",
    vsCompetitor: "Career coaches charge $200+/session. Same gap analysis with specific courses and portfolio projects — $1.56.",
    route: "skills_gap",
  },
  {
    id: "roadmap",
    icon: "Map",
    title: "Career Roadmap",
    description: "A dual-track plan: land the job AND build income on the side — with weekly checkpoints",
    tokens: 15,
    category: "Grow",
    phase: 3,
    painPoint: "53% of professionals plan to switch careers by end of 2026. The ones who succeed have a written plan with deadlines.",
    vsCompetitor: "Career coaches charge $500+ for a plan. Ours includes an income-building track alongside job hunting — $2.93.",
    route: "roadmap",
  },
  {
    id: "salary",
    icon: "DollarSign",
    title: "Salary Negotiation",
    description: "Know your worth, rehearse the conversation, and negotiate beyond just base salary",
    tokens: 8,
    category: "Prepare",
    phase: 3,
    painPoint: "27% of employees say AI inflated their salary expectations. We give you honest ranges with verification sources.",
    vsCompetitor: "Levels.fyi costs $12/mo for data alone. We add leverage assessment + word-for-word negotiation scripts — $1.56.",
    route: "salary",
  },
  {
    id: "entrepreneurship",
    icon: "Rocket",
    title: "Entrepreneurship",
    description: "Discover which business you could build with the skills you already have — starting this week",
    tokens: 12,
    category: "Grow",
    phase: 4,
    painPoint: "90% of funded startups fail. But bootstrapped services based on existing expertise? Much higher success rates.",
    vsCompetitor: "Startup coaches charge $300+ per session. Full founder-market-fit assessment with a 90-day launch plan — $2.34.",
    route: "entrepreneurship",
  },
];

export const TOOL_CATEGORIES = ["Analyze", "Build", "Prepare", "Grow"] as const;

/* ------------------------------------------------------------------ */
/*  Profile Completeness (single source of truth)                     */
/* ------------------------------------------------------------------ */

export interface ProfileCompletenessItem {
  label: string;
  done: boolean;
  href: string;
}

export interface ProfileCompleteness {
  score: number;
  items: ProfileCompletenessItem[];
}

/** Calculate how complete the user's profile is (0–100). */
export function calculateProfileCompleteness(
  careerProfile: CareerProfile | null,
  activeJobTarget: JobTarget | null,
): ProfileCompleteness {
  const skills: Json | undefined = careerProfile?.skills;
  const hasSkills = Array.isArray(skills) && skills.length > 0;

  const items: ProfileCompletenessItem[] = [
    {
      label: "Add your resume",
      done: !!careerProfile?.resume_text,
      href: "/settings",
    },
    {
      label: "Set a job target",
      done: !!activeJobTarget,
      href: "/mission",
    },
    {
      label: "Add title & industry",
      done: !!(careerProfile?.title && careerProfile?.industry),
      href: "/settings",
    },
    {
      label: "Specify target role",
      done: !!activeJobTarget?.title,
      href: "/mission",
    },
    {
      label: "Add your skills",
      done: hasSkills,
      href: "/settings",
    },
    {
      label: "Set years of experience",
      done: careerProfile?.years_experience != null,
      href: "/settings",
    },
  ];

  // Account created = +10 (always true when logged in)
  let score = 10;
  if (careerProfile?.resume_text) score += 30;
  if (activeJobTarget) score += 20;
  if (careerProfile?.title && careerProfile?.industry) score += 15;
  if (activeJobTarget?.title) score += 10;
  if (hasSkills) score += 10;
  if (careerProfile?.years_experience != null) score += 5;

  return { score, items };
}

export const INDUSTRIES = [
  "Technology",
  "Finance & Banking",
  "Healthcare",
  "Education",
  "Marketing & Advertising",
  "Legal",
  "Manufacturing",
  "Retail & E-commerce",
  "Media & Entertainment",
  "Consulting",
  "Real Estate",
  "Government",
  "Nonprofit",
  "Other",
] as const;

export const TOOLS_MAP = Object.fromEntries(
  TOOLS.map((t) => [t.id, t])
) as Record<string, Tool>;

export const PACKS: Pack[] = [
  {
    id: "starter",
    name: "Starter",
    tokens: 50,
    price: 14,
    rate: "$0.28",
    description: "Try 2–3 tools",
  },
  {
    id: "pro",
    name: "Pro",
    tokens: 200,
    price: 39,
    rate: "$0.195",
    description: "Full career overhaul",
    highlighted: true,
    save: "30%",
    vsNote: "Same price as one month of Teal — but covers months of 10 premium AI career tools.",
  },
  {
    id: "power",
    name: "Power",
    tokens: 500,
    price: 79,
    rate: "$0.158",
    description: "Career transformation",
    save: "44%",
    vsNote: "Less than 2 months of Jobscan — but covers 6+ months of career work with every tool.",
  },
];

export const FAQ_ITEMS = [
  // Core product questions
  {
    q: "How does the token system work?",
    a: "Tokens are your currency for using AI tools. Each tool costs a specific number of tokens — from free (AI Displacement Score) to 25 tokens (AI Headshots). Buy token packs starting at $14, and use them whenever you want. Tokens never expire. You also earn free tokens every day just by logging in.",
  },
  {
    q: "Is the AI Displacement Score really free?",
    a: "Yes, the AI Displacement Score is completely free to use — no tokens, no credit card, no catch. We believe everyone should understand their career risk from AI automation. The tool analyzes your role against ILO 2025 data and shows which of your tasks AI can replace and which it can't. Sign up to get 15 additional free tokens for other tools.",
  },
  {
    q: "How is AISkillScore different from Jobscan or Teal?",
    a: "AISkillScore offers 11 AI career tools in one platform, priced per-use instead of $348–$1,788/year subscriptions. Jobscan ($599/year) only counts keywords — we show evidence from your actual resume. Teal ($348/year) uses generic templates — we preserve your authentic voice. FinalRound ($1,788/year) preps first answers — we prep follow-up questions too. A full job application stack costs under $8. You only pay for what you use, starting at free.",
  },
  {
    q: "Is my data safe and private?",
    a: "Absolutely. We use AES-256 encryption at rest, never sell your data to third parties, and auto-delete all personal data after 90 days of inactivity. AI processing happens via API calls with no data retention on AI provider servers. You can export or delete your data at any time from Settings. We're GDPR compliant.",
  },
  // AI-query-optimized questions (natural language queries people ask AI assistants)
  {
    q: "What is the best AI tool to check if my resume will pass ATS?",
    a: "AISkillScore's Resume Optimizer (15 tokens, about $2.93) analyzes your resume against ATS requirements and rewrites it to pass automated screening while preserving your authentic voice. Unlike tools that just count keywords, it provides evidence-based optimization — showing exactly why each change improves your ATS pass rate. Your first resume optimization is free with signup tokens. The JD Match Score (5 tokens) also checks how well your resume matches a specific job posting.",
  },
  {
    q: "How do I know if AI will replace my job?",
    a: "AISkillScore's AI Displacement Score is a free tool that analyzes your specific role against ILO 2025 research data. It breaks down which of your daily tasks AI can automate and which require human judgment, creativity, or interpersonal skills. The score ranges from 0–100, with higher numbers meaning higher automation risk. 1 in 4 roles are exposed to generative AI according to ILO 2025 data.",
  },
  {
    q: "What AI tools help with job searching in 2026?",
    a: "AISkillScore provides 11 AI-powered career tools: AI Displacement Score (free), JD Match Score for job-resume matching, Resume Optimizer for ATS optimization, Cover Letter generator, LinkedIn Optimizer for recruiter algorithm visibility, AI Headshots, Interview Prep with follow-up questions, Skills Gap Analysis, Career Roadmap with weekly checkpoints, Salary Negotiation scripts, and Entrepreneurship Assessment. All tools use Gemini 2.5 Pro AI and are pay-per-use with no subscriptions. Token packs start at $14.",
  },
  {
    q: "Is AI resume optimization worth paying for?",
    a: "Yes — 43% of ATS rejections are formatting errors, not qualification gaps (source: JobScan research). A single missed keyword can eliminate an otherwise qualified candidate. AISkillScore's Resume Optimizer costs 15 tokens (about $2.93) versus career coaches at $200+/session or Jobscan at $599/year — and your first one is free with signup tokens. The ROI is significant: even one additional interview from better ATS pass rates is worth hundreds of times the cost.",
  },
  // Pricing & value
  {
    q: "What's the Lifetime Deal?",
    a: "For $119 one-time (early bird), you get 120 tokens refilled every month forever — that's enough for a full application stack plus extra tools each month. You break even in about 3 months versus buying Pro packs. Early bird pricing is limited to 500 spots, after which the price increases to $179. VIP tier ($279) includes 180 tokens/month. 30-day money-back guarantee included.",
  },
  {
    q: "How is the Lifetime Deal different from token packs?",
    a: "Token packs are one-time purchases. The Lifetime Deal (from $119) refills 120 tokens every month forever (180 for VIP), with a 300 token cap. Need more in a busy month? Top up with any pack.",
  },
  {
    q: "Can I get a refund?",
    a: "Token packs are non-refundable since tokens are delivered instantly. However, the Lifetime Deal comes with a 30-day money-back guarantee — if you're not satisfied, we'll refund you in full, no questions asked.",
  },
  {
    q: "Do I get free tokens every day?",
    a: "Yes! Log in daily and receive 2 free tokens. Save up for a few days and run a JD Match scan. Consistency wins the job hunt.",
  },
  // Trust & quality
  {
    q: "Will recruiters know my resume was AI-optimized?",
    a: "Not with AISkillScore. Unlike other tools that rewrite your resume into generic 'spearheaded' language, we enhance YOUR voice. Our #1 rule: no detectable AI cliches.",
  },
  {
    q: "What AI model does AISkillScore use?",
    a: "All 11 tools use Google's Gemini 2.5 Pro — one of the most capable AI models available in 2026. We chose quality over cost: instead of using cheaper models, every analysis gets premium AI processing. This means more accurate scores, better resume rewrites, and more relevant interview prep. Results are delivered in about 15-30 seconds.",
  },
  {
    q: "Can AISkillScore help me make money while job hunting?",
    a: "Yes. Every tool surfaces freelance and consulting opportunities based on your skills. The Entrepreneurship Assessment and Career Roadmap include income-building plans you can start this week.",
  },
  {
    q: "What data does the AI use about me?",
    a: "Only what you provide: your resume text, job descriptions you paste, and any career profile info you enter. We never scrape your accounts, and we auto-delete data after 90 days.",
  },
  {
    q: "How accurate are the AI career scores?",
    a: "AISkillScore's analyses are powered by Gemini 2.5 Pro and grounded in real data — ILO 2025 research for displacement scores, BLS salary data for negotiations, and industry-standard ATS parsing rules for resume optimization. Every score comes with evidence and citations, not just a number. However, AI analysis should be used as guidance alongside your own judgment, not as a guarantee of outcomes.",
  },
];

export const MISSION_ACTIONS = [
  {
    id: "optimize",
    toolId: "resume" as const,
    title: "Optimize Resume",
    description: "Rewrite your resume to match this job's requirements and pass ATS",
    tokens: 15,
    impact: "High",
    priority: "Critical" as const,
    track: "A" as const,
  },
  {
    id: "cover",
    toolId: "cover_letter" as const,
    title: "Write Cover Letter",
    description: "Generate a tailored cover letter citing your real experience",
    tokens: 8,
    impact: "Medium",
    priority: "High" as const,
    track: "A" as const,
  },
  {
    id: "skills",
    toolId: "skills_gap" as const,
    title: "Analyze Skills Gap",
    description: "Identify missing skills and get a learning path to close them",
    tokens: 8,
    impact: "Medium",
    priority: "Medium" as const,
    track: "A" as const,
  },
  {
    id: "interview",
    toolId: "interview" as const,
    title: "Prepare for Interview",
    description: "Practice company-specific questions with AI-coached answers",
    tokens: 8,
    impact: "High",
    priority: "High" as const,
    track: "A" as const,
  },
  {
    id: "salary",
    toolId: "salary" as const,
    title: "Research Salary",
    description: "Get market data and negotiation scripts for your target role",
    tokens: 8,
    impact: "Medium",
    priority: "Medium" as const,
    track: "A" as const,
  },
];

export const INCOME_ACTIONS = [
  {
    id: "entrepreneurship",
    toolId: "entrepreneurship" as const,
    title: "Entrepreneurship Assessment",
    description: "Discover income opportunities from your existing skills — start earning this week",
    tokens: 12,
    impact: "High",
    priority: "Medium" as const,
    track: "B" as const,
  },
  {
    id: "linkedin_brand",
    toolId: "linkedin" as const,
    title: "LinkedIn Monetization",
    description: "Build a personal brand that generates income and attracts opportunities",
    tokens: 15,
    impact: "Medium",
    priority: "Low" as const,
    track: "B" as const,
  },
  {
    id: "roadmap_income",
    toolId: "roadmap" as const,
    title: "Dual-Track Roadmap",
    description: "Create a plan that combines job hunting with income building",
    tokens: 15,
    impact: "High",
    priority: "Medium" as const,
    track: "B" as const,
  },
];
