import type { Tool, Pack } from "@/types";

export const TOOLS: Tool[] = [
  {
    id: "displacement",
    icon: "ShieldAlert",
    title: "AI Displacement Score",
    description: "How likely is AI to impact your role in 2-5 years?",
    tokens: 0,
    category: "Analyze",
    phase: 1,
    painPoint: "47% of jobs face significant AI disruption by 2030",
    vsCompetitor: null,
    route: "displacement",
  },
  {
    id: "jd_match",
    icon: "Target",
    title: "JD Match Score",
    description: "See exactly how you match against any job posting",
    tokens: 2,
    category: "Analyze",
    phase: 1,
    painPoint: "75% of resumes are auto-rejected by ATS before a human sees them",
    vsCompetitor: "Jobscan charges $49.95/mo for just resume scanning",
    route: "jd_match",
  },
  {
    id: "resume",
    icon: "FileText",
    title: "Resume Optimizer",
    description: "AI rewrites your resume to pass ATS and impress recruiters",
    tokens: 10,
    category: "Build",
    phase: 1,
    painPoint: "75% of resumes are auto-rejected by ATS before a human sees them",
    vsCompetitor: "Jobscan charges $49.95/mo. We charge 10 tokens (~$0.75)",
    route: "resume",
  },
  {
    id: "cover_letter",
    icon: "Mail",
    title: "Cover Letter Generator",
    description: "Tailored cover letter matching job requirements to your experience",
    tokens: 3,
    category: "Build",
    phase: 2,
    painPoint: "Hiring managers spend 7 seconds scanning a cover letter",
    vsCompetitor: "Resume Genius charges $7.95/letter. We charge 3 tokens (~$0.23)",
    route: "cover_letter",
  },
  {
    id: "linkedin",
    icon: "Linkedin",
    title: "LinkedIn Optimizer",
    description: "Optimize your profile headline, about, and keywords for recruiter search",
    tokens: 10,
    category: "Build",
    phase: 2,
    painPoint: "87% of recruiters use LinkedIn to find candidates",
    vsCompetitor: "Teal charges $29/mo for LinkedIn tools. We charge 10 tokens (~$0.75)",
    route: "linkedin",
  },
  {
    id: "headshots",
    icon: "Camera",
    title: "AI Pro Headshots",
    description: "Professional headshots generated from your selfies",
    tokens: 20,
    category: "Build",
    phase: 2,
    painPoint: "Profiles with professional photos get 14x more views",
    vsCompetitor: "HeadshotPro charges $29+. We charge 20 tokens (~$1.50)",
    route: "headshots",
  },
  {
    id: "interview",
    icon: "MessageSquare",
    title: "Interview Prep",
    description: "Company-specific questions with AI-coached answers",
    tokens: 3,
    category: "Prepare",
    phase: 3,
    painPoint: "Top candidates practice 3x more interview questions",
    vsCompetitor: "FinalRound charges $149/mo. We charge 3 tokens (~$0.23)",
    route: "interview",
  },
  {
    id: "skills_gap",
    icon: "TrendingUp",
    title: "Skills Gap Analysis",
    description: "Identify skill gaps and get a personalized learning path",
    tokens: 5,
    category: "Grow",
    phase: 3,
    painPoint: "65% of job seekers lack at least one critical skill for their target role",
    vsCompetitor: "Career coaches charge $200+/session for gap analysis",
    route: "skills_gap",
  },
  {
    id: "roadmap",
    icon: "Map",
    title: "Career Roadmap",
    description: "6-12 month action plan with milestones and checkpoints",
    tokens: 8,
    category: "Grow",
    phase: 3,
    painPoint: "Only 23% of professionals have a written career development plan",
    vsCompetitor: "Career coaching packages start at $500+. We charge 8 tokens (~$0.60)",
    route: "roadmap",
  },
  {
    id: "salary",
    icon: "DollarSign",
    title: "Salary Negotiation",
    description: "Market data, counter-offer scripts, and negotiation tactics",
    tokens: 3,
    category: "Prepare",
    phase: 3,
    painPoint: "58% of workers never negotiate salary, leaving $7,500+/year on the table",
    vsCompetitor: "Levels.fyi Pro costs $12/mo. We charge 3 tokens (~$0.23)",
    route: "salary",
  },
  {
    id: "entrepreneurship",
    icon: "Rocket",
    title: "Entrepreneurship Assessment",
    description: "Founder-market fit analysis and business model matching",
    tokens: 8,
    category: "Grow",
    phase: 4,
    painPoint: "90% of startups fail, often due to poor founder-market fit",
    vsCompetitor: null,
    route: "entrepreneurship",
  },
];

export const TOOL_CATEGORIES = ["Analyze", "Build", "Prepare", "Grow"] as const;

export const TOOLS_MAP = Object.fromEntries(
  TOOLS.map((t) => [t.id, t])
) as Record<string, Tool>;

export const PACKS: Pack[] = [
  {
    id: "starter",
    name: "Starter",
    tokens: 50,
    price: 5,
    rate: "$0.10",
    description: "Try 2–3 tools",
  },
  {
    id: "pro",
    name: "Pro",
    tokens: 200,
    price: 15,
    rate: "$0.075",
    description: "Full career overhaul",
    highlighted: true,
    save: "25%",
    vsNote: "Jobscan = $49.95/mo for just resume scanning",
  },
  {
    id: "power",
    name: "Power",
    tokens: 600,
    price: 39,
    rate: "$0.065",
    description: "Career transformation",
    save: "35%",
  },
];

export const FAQ_ITEMS = [
  {
    q: "How does the token system work?",
    a: "Tokens are your currency for using AI tools. Each tool costs a specific number of tokens. Buy token packs starting at $5, and use them whenever you want — tokens never expire.",
  },
  {
    q: "Is the AI Displacement Score really free?",
    a: "Yes! The AI Displacement Score is completely free to use. We want everyone to understand their career risk. Sign up to get 5 additional free tokens for other tools.",
  },
  {
    q: "How is this different from Jobscan or Teal?",
    a: "We offer 11 AI tools in one platform, priced per-use instead of $29-$149/month subscriptions. You only pay for what you use, and our tools go beyond just resume scanning.",
  },
  {
    q: "Is my data safe?",
    a: "Absolutely. We use AES-256 encryption at rest, never sell your data, and auto-delete after 90 days. AI processing happens via API with no data retention.",
  },
  {
    q: "What's the Lifetime Deal?",
    a: "For $49 one-time, you get 100 tokens refilled every month forever. That covers multiple full job applications each month. Early bird pricing is limited.",
  },
  {
    q: "Can I get a refund?",
    a: "Token packs are non-refundable, but the Lifetime Deal comes with a 30-day money-back guarantee. If you're not satisfied, we'll refund you in full.",
  },
];

export const MISSION_ACTIONS = [
  {
    id: "optimize",
    toolId: "resume" as const,
    title: "Optimize Resume",
    description: "Rewrite your resume to match this job's requirements and pass ATS",
    tokens: 10,
    impact: "High",
    priority: "Critical" as const,
  },
  {
    id: "cover",
    toolId: "cover_letter" as const,
    title: "Write Cover Letter",
    description: "Generate a tailored cover letter citing your real experience",
    tokens: 3,
    impact: "Medium",
    priority: "High" as const,
  },
  {
    id: "skills",
    toolId: "skills_gap" as const,
    title: "Analyze Skills Gap",
    description: "Identify missing skills and get a learning path to close them",
    tokens: 5,
    impact: "Medium",
    priority: "Medium" as const,
  },
  {
    id: "interview",
    toolId: "interview" as const,
    title: "Prepare for Interview",
    description: "Practice company-specific questions with AI-coached answers",
    tokens: 3,
    impact: "High",
    priority: "High" as const,
  },
  {
    id: "salary",
    toolId: "salary" as const,
    title: "Research Salary",
    description: "Get market data and negotiation scripts for your target role",
    tokens: 3,
    impact: "Medium",
    priority: "Medium" as const,
  },
];
