// Loading insights shown while AI tools are processing.
// Each tool has its own curated set of tips, stats, quotes, and pain/solution pairs.
// These rotate every few seconds to educate and engage users during the wait.

export type InsightCategory = "tip" | "stat" | "quote" | "pain_solution";

export interface LoadingInsight {
  category: InsightCategory;
  text: string;
  /** Optional secondary text — source attribution for stats, author for quotes */
  source?: string;
}

const UNIVERSAL_INSIGHTS: LoadingInsight[] = [
  { category: "quote", text: "The best time to plant a tree was 20 years ago. The second best time is now.", source: "Chinese Proverb" },
  { category: "quote", text: "Your career is a marathon, not a sprint. Every step you take today compounds.", source: "Reid Hoffman, LinkedIn Co-founder" },
  { category: "stat", text: "Professionals who actively manage their career development earn 20-30% more over their lifetime.", source: "Harvard Business Review" },
  { category: "tip", text: "Our AI is using advanced reasoning to deeply analyze your specific situation — not generic templates." },
  { category: "tip", text: "Every analysis is personalized to your actual experience, skills, and target role." },
];

const TOOL_INSIGHTS: Record<string, LoadingInsight[]> = {
  displacement: [
    { category: "stat", text: "1 in 4 roles are now exposed to generative AI disruption.", source: "ILO 2025 Report" },
    { category: "stat", text: "47% of jobs face significant AI transformation by 2030 — but most will evolve, not disappear.", source: "McKinsey Global Institute" },
    { category: "pain_solution", text: "The problem: Most workers don't know which of their daily tasks are at risk. The solution: We decompose your role into specific tasks and name the exact AI tools that threaten each one." },
    { category: "tip", text: "Your score analyzes your specific role, not generic occupation data. We look at what YOU do every day." },
    { category: "quote", text: "The illiterate of the 21st century will not be those who cannot read and write, but those who cannot learn, unlearn, and relearn.", source: "Alvin Toffler" },
    { category: "stat", text: "Workers who proactively upskill around AI earn 15-40% more than peers who don't.", source: "World Economic Forum" },
    { category: "tip", text: "We don't just show risk — we show you exactly how to use AI as a tool to become more productive, not be replaced." },
    { category: "pain_solution", text: "The fear: AI will take my job. The reality: AI will transform your job. Those who adapt will thrive. We'll show you how." },
    { category: "quote", text: "The future belongs to those who learn more skills and combine them in creative ways.", source: "Robert Greene" },
    { category: "stat", text: "Professionals who augment their work with AI tools report 40% higher productivity within 3 months.", source: "Stanford HAI 2025" },
  ],

  jd_match: [
    { category: "stat", text: "75% of resumes are rejected by ATS systems before a human ever sees them.", source: "Jobscan Research" },
    { category: "stat", text: "On average, each corporate job posting receives 250 applications. Only 4-6 get interviews.", source: "Glassdoor" },
    { category: "pain_solution", text: "The problem: Keyword-matching tools count words. The solution: We evaluate you the way a real recruiter does — semantic skill matching, career trajectory, and competitive positioning." },
    { category: "tip", text: "We quote exact text from your resume as evidence for each match — so you know exactly what's working." },
    { category: "quote", text: "It's not about having the right opportunities. It's about handling the opportunities right.", source: "Mark Hunter" },
    { category: "stat", text: "Candidates who tailor their resume to each job description are 3x more likely to get an interview.", source: "CareerBuilder" },
    { category: "tip", text: "A 'stretch' application with a strong cover letter and referral often beats a 'perfect match' with a generic application." },
    { category: "pain_solution", text: "Jobscan charges $599/year for keyword counting. We analyze semantic matches, hidden requirements, and competitive positioning — for $0.18 per analysis." },
    { category: "quote", text: "Opportunities don't happen. You create them.", source: "Chris Grosser" },
    { category: "stat", text: "Referred candidates are 4x more likely to be hired. Our analysis includes referral strategy advice.", source: "LinkedIn Talent Solutions" },
  ],

  resume: [
    { category: "stat", text: "43% of ATS rejections come from formatting errors — not qualification gaps.", source: "TopResume Study" },
    { category: "stat", text: "Recruiters spend an average of 7.4 seconds on initial resume screening.", source: "Ladders Eye-Tracking Study" },
    { category: "pain_solution", text: "The problem: 25% of resumes are flagged as AI-generated by recruiters. The solution: We enhance YOUR voice — no generic 'spearheaded' or 'leveraged' language." },
    { category: "tip", text: "Our AI preserves your authentic writing style while optimizing for ATS parsing and keyword alignment." },
    { category: "quote", text: "A resume is not a list of tasks. It's a marketing document that tells the story of your impact.", source: "Laszlo Bock, former SVP People Operations at Google" },
    { category: "stat", text: "Resumes with quantified achievements receive 40% more interview callbacks.", source: "TalentWorks" },
    { category: "tip", text: "We check your resume against all major ATS systems: Greenhouse, Lever, Workday, and iCIMS." },
    { category: "pain_solution", text: "Other tools rewrite your resume into corporate jargon. We strengthen what's already there — your real experience, your real impact." },
    { category: "quote", text: "The secret of getting ahead is getting started.", source: "Mark Twain" },
    { category: "stat", text: "A well-optimized resume can increase your interview rate by 50-70%.", source: "Zety Career Research" },
  ],

  cover_letter: [
    { category: "stat", text: "Recruiters trash 'I am writing to express my interest' letters instantly. Storytelling wins.", source: "38-year veteran recruiter survey" },
    { category: "stat", text: "45% of hiring managers say a great cover letter can make them consider an otherwise unqualified candidate.", source: "CareerBuilder" },
    { category: "pain_solution", text: "The problem: Template cover letters all sound the same. The solution: We write from YOUR story — specific moments, real achievements, genuine enthusiasm." },
    { category: "tip", text: "Your cover letter should add context the resume can't — personality, motivation, and a narrative that connects your past to their future." },
    { category: "quote", text: "People don't buy what you do, they buy why you do it.", source: "Simon Sinek" },
    { category: "stat", text: "Cover letters with specific company references are 2x more likely to generate an interview.", source: "ResumeGo" },
    { category: "tip", text: "We never use 'Dear Hiring Manager' or 'I look forward to hearing from you.' Our letters sound like a smart, enthusiastic person — not a template." },
    { category: "pain_solution", text: "Resume Genius charges $7.95 per template letter. We write a truly personalized letter from your actual experience for just 3 tokens." },
    { category: "quote", text: "Tell me a fact and I'll learn. Tell me a truth and I'll believe. But tell me a story and it will live in my heart forever.", source: "Native American Proverb" },
    { category: "stat", text: "The most memorable cover letter a veteran recruiter ever read opened with raw, personal storytelling — not credentials." },
  ],

  interview: [
    { category: "stat", text: "90% of candidates aren't prepared for follow-up questions — that's where interviews are won or lost.", source: "Interview coaching data" },
    { category: "stat", text: "The average candidate prepares for 10 hours before an interview. Top performers prepare for 20+.", source: "Indeed Survey" },
    { category: "pain_solution", text: "The problem: Most prep focuses on the first answer. The solution: We prep you for the follow-ups that test whether you actually did what you claim." },
    { category: "tip", text: "We design questions in progression: warm-up → behavioral → technical → gap-probing. Just like a real interview." },
    { category: "quote", text: "Before anything else, preparation is the key to success.", source: "Alexander Graham Bell" },
    { category: "stat", text: "Candidates who practice with follow-up questions are 3x more likely to receive offers.", source: "Interview performance studies" },
    { category: "tip", text: "Each suggested answer includes a 'power phrase' — one standout sentence that makes the interviewer write a positive note." },
    { category: "pain_solution", text: "FinalRound charges $1,788/year to prep first answers. We prep follow-ups too — for 3 tokens (~$0.29)." },
    { category: "quote", text: "Success is where preparation meets opportunity.", source: "Bobby Unser" },
    { category: "stat", text: "77% of interviewers say 'Tell me about yourself' is the most important question. We coach you on the perfect 90-second response." },
  ],

  linkedin: [
    { category: "stat", text: "LinkedIn's AI Hiring Assistant now screens profiles before recruiters see them. Your first 3 sentences matter most.", source: "LinkedIn 2026" },
    { category: "stat", text: "Profiles with professional photos get 14x more views. Profiles with regular content get 47% more inbound opportunities.", source: "LinkedIn Data" },
    { category: "pain_solution", text: "The problem: LinkedIn's algorithm changed in 2026. The solution: We optimize for the new AI Hiring Assistant that summarizes your profile for recruiters." },
    { category: "tip", text: "Your About section's first 3 sentences are what LinkedIn's AI extracts as your 'Value Prop' for recruiters." },
    { category: "quote", text: "Your brand is what people say about you when you're not in the room.", source: "Jeff Bezos" },
    { category: "stat", text: "Users who post once a week see a 5x increase in profile views within 90 days.", source: "LinkedIn Creator Analytics" },
    { category: "tip", text: "We generate 3 headline variations: one for recruiter search, one for peer discovery, one for thought leadership." },
    { category: "pain_solution", text: "Teal charges $348/year to optimize text. We optimize for LinkedIn's 2026 AI algorithm — the one that actually decides if recruiters see you." },
    { category: "quote", text: "Networking is not about collecting contacts. It's about planting relations.", source: "Torsten Siever" },
    { category: "stat", text: "68% of recruiters use LinkedIn as their primary sourcing tool. If your profile isn't optimized, you're invisible." },
  ],

  skills_gap: [
    { category: "stat", text: "42% of professionals can't articulate their transferable skills — they undervalue what they already have.", source: "LinkedIn Workforce Report" },
    { category: "stat", text: "The average skill has a half-life of 5 years. Continuous learning isn't optional anymore.", source: "World Economic Forum" },
    { category: "pain_solution", text: "The problem: You focus on what's missing. The solution: We start with your strengths, then show exactly how close you already are to your target role." },
    { category: "tip", text: "Most career transitioners are closer than they think. We identify transferable skills that partially or fully cover target requirements." },
    { category: "quote", text: "The only person you are destined to become is the person you decide to be.", source: "Ralph Waldo Emerson" },
    { category: "stat", text: "Professionals who close 2-3 critical skill gaps increase their salary potential by 15-25%.", source: "Coursera Skills Report" },
    { category: "tip", text: "We recommend specific courses with real names, platforms, costs, and completion times — not vague 'learn more about X' advice." },
    { category: "pain_solution", text: "Career coaches charge $200+ per session for skills assessment. We provide the same depth of analysis with named courses and portfolio projects — for 5 tokens." },
    { category: "quote", text: "An investment in knowledge pays the best interest.", source: "Benjamin Franklin" },
    { category: "stat", text: "Adding even one in-demand certification increases interview callbacks by 20%.", source: "Indeed Hiring Lab" },
  ],

  roadmap: [
    { category: "stat", text: "53% of professionals plan to switch careers by end of 2026. Those with a plan succeed 4x more often.", source: "PwC Workforce Study" },
    { category: "stat", text: "Career transitions take 3-12 months on average. A structured plan cuts that time by 40%.", source: "Career coaching data" },
    { category: "pain_solution", text: "The problem: Vague plans fail. The solution: Every milestone has a measurable checkpoint, a specific deadline, and a backup plan." },
    { category: "tip", text: "We build a dual-track plan: Track A for job hunting and Track B for income building. Both reinforce each other." },
    { category: "quote", text: "A goal without a plan is just a wish.", source: "Antoine de Saint-Exupery" },
    { category: "stat", text: "Professionals who build income while job hunting report 70% less financial stress and make better career decisions.", source: "Career resilience research" },
    { category: "tip", text: "Your roadmap includes specific networking scripts — not just 'expand your network' but actual messages to send this week." },
    { category: "pain_solution", text: "Career coaches charge $500+ for a career plan. Your personalized 12-month roadmap with weekly checkpoints costs 8 tokens." },
    { category: "quote", text: "The future depends on what you do today.", source: "Mahatma Gandhi" },
    { category: "stat", text: "Candidates who network strategically (quality over quantity) receive 10x more interview invitations.", source: "LinkedIn Talent Solutions" },
  ],

  salary: [
    { category: "stat", text: "Most candidates leave $5,000-$15,000 on the table by not negotiating. That compounds to $500K+ over a career.", source: "Salary.com" },
    { category: "stat", text: "84% of employers expect candidates to negotiate. Not doing so can actually count against you.", source: "Robert Half" },
    { category: "pain_solution", text: "The problem: You don't know your leverage. The solution: We assess your specific negotiation position before giving you scripts." },
    { category: "tip", text: "Negotiation outcomes depend on leverage more than scripts. We assess your position first, then tailor the exact words to your situation." },
    { category: "quote", text: "You don't get what you deserve. You get what you negotiate.", source: "Chester L. Karrass" },
    { category: "stat", text: "Candidates who negotiate salary receive an average of 7-10% more than the initial offer.", source: "PayScale" },
    { category: "tip", text: "We provide word-for-word scripts you can use verbatim — including what to say if they push back." },
    { category: "pain_solution", text: "Levels.fyi charges $12/month for salary data. We add personalized negotiation scripts, leverage assessment, and freelance rate guidance." },
    { category: "quote", text: "Know your worth. Then add tax.", source: "Unknown" },
    { category: "stat", text: "The best time to negotiate is after they say 'We'd like to offer you the position' — not before.", source: "Negotiation research" },
  ],

  entrepreneurship: [
    { category: "stat", text: "Bootstrapped services built on existing expertise outperform most funded startups in the first 2 years.", source: "Indie Hackers data" },
    { category: "stat", text: "70% of successful entrepreneurs started their business while still employed. You don't need to quit first.", source: "Harvard Business Review" },
    { category: "pain_solution", text: "The problem: You think entrepreneurship means building an app. The solution: The best businesses start with what you already know — consulting, freelancing, productized services." },
    { category: "tip", text: "We evaluate 5 business models for your specific skills — from freelance consulting ($0 startup) to productized services to SaaS." },
    { category: "quote", text: "The best businesses solve problems their founders deeply understand from personal experience.", source: "Paul Graham, Y Combinator" },
    { category: "stat", text: "Freelance consultants in specialized niches earn $100-300/hour. Your industry expertise is more valuable than you think.", source: "Upwork Data" },
    { category: "tip", text: "Every business model we suggest can run alongside active job hunting — building your portfolio AND generating income simultaneously." },
    { category: "pain_solution", text: "The fear: I'm not an entrepreneur. The reality: If you've solved problems at work, you already have the core skill. We show you how to package it." },
    { category: "quote", text: "Don't find customers for your products. Find products for your customers.", source: "Seth Godin" },
    { category: "stat", text: "The median time to first revenue for consulting businesses is 14 days. For productized services, 30 days.", source: "MicroConf Research" },
  ],

  headshots: [
    { category: "stat", text: "Profiles with professional headshots get 14x more views and 36% more messages.", source: "LinkedIn Data" },
    { category: "stat", text: "First impressions are formed in 7 seconds — your profile photo is often the very first thing people see.", source: "Princeton Psychology Research" },
    { category: "pain_solution", text: "The problem: Professional photography costs $200-500. The solution: AI-generated headshots that look natural and professional — for 20 tokens." },
    { category: "tip", text: "Our AI maintains your actual facial features and expression while enhancing lighting, background, and professional styling." },
    { category: "quote", text: "You never get a second chance to make a first impression.", source: "Will Rogers" },
    { category: "stat", text: "Recruiters are 70% more likely to click on a profile with a clear, professional headshot.", source: "LinkedIn Recruiter Study" },
    { category: "tip", text: "We generate multiple styles — professional, casual, and modern — so you can choose what fits your industry." },
    { category: "pain_solution", text: "HeadshotPro charges $29+. We use the same AI technology for a fraction of the cost." },
  ],
};

/**
 * Returns a shuffled array of loading insights for a specific tool.
 * Mixes tool-specific insights with universal ones.
 */
export function getLoadingInsights(toolId: string): LoadingInsight[] {
  const toolSpecific = TOOL_INSIGHTS[toolId] || [];
  const combined = [...toolSpecific, ...UNIVERSAL_INSIGHTS];
  // Shuffle using Fisher-Yates
  for (let i = combined.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [combined[i], combined[j]] = [combined[j], combined[i]];
  }
  return combined;
}
