/**
 * Centralized sourced statistics, expert quotes, and pain/solution pairs.
 * All data extracted from SPRINT_NEXT.md research (2025-2026 sources).
 * Used by StatBlock, PainSolution, ExpertQuote, and CompetitorAnchor components.
 */

export interface TStat {
  value: string;
  label: string;
  source: string;
}

export interface TPainSolution {
  pain: string;
  solution: string;
  source?: string;
}

export interface TExpertQuote {
  quote: string;
  attribution: string;
  role?: string;
}

export interface TCompetitorPrice {
  name: string;
  price: string;
  period: string;
}

// ─── ATS & Resume Stats ─────────────────────────────────────

export const ATS_STATS: TStat[] = [
  { value: "75%", label: "of resumes rejected before a human sees them", source: "Jobscan Research" },
  { value: "43%", label: "of ATS rejections are formatting errors, not qualifications", source: "TopResume Study" },
  { value: "7.4s", label: "average recruiter resume screening time", source: "Ladders Eye-Tracking Study" },
  { value: "25%", label: "of resumes flagged as AI-generated by recruiters", source: "2026 Recruiter Survey" },
  { value: "78%", label: "of ATS platforms now use ML semantic matching", source: "2025 ATS Technology Report" },
  { value: "60%", label: "of resumes fail at document structure parsing alone", source: "2025 ATS Technology Report" },
  { value: "40%", label: "more interview callbacks with quantified achievements", source: "TalentWorks" },
  { value: "3x", label: "more likely to get interviewed with a tailored resume", source: "CareerBuilder" },
];

// ─── AI Displacement Stats ──────────────────────────────────

export const AI_DISPLACEMENT_STATS: TStat[] = [
  { value: "1 in 4", label: "workers globally have roles exposed to generative AI", source: "ILO 2025 Report" },
  { value: "47%", label: "of jobs face significant AI transformation by 2030", source: "McKinsey Global Institute" },
  { value: "40%", label: "higher productivity for workers who augment with AI tools", source: "Stanford HAI 2025" },
  { value: "15-40%", label: "more earnings for workers who proactively upskill around AI", source: "World Economic Forum" },
];

// ─── Interview Stats ────────────────────────────────────────

export const INTERVIEW_STATS: TStat[] = [
  { value: "250", label: "applications per corporate job posting — only 4-6 get interviews", source: "Glassdoor" },
  { value: "4x", label: "more likely to be hired when referred by an employee", source: "LinkedIn Talent Solutions" },
  { value: "90%", label: "of candidates unprepared for follow-up questions", source: "Interview coaching research" },
];

// ─── Salary Stats ───────────────────────────────────────────

export const SALARY_STATS: TStat[] = [
  { value: "76%", label: "of professionals who negotiate earn $5K-$10K more", source: "Salary.com" },
  { value: "27%", label: "of employees say AI inflates their salary expectations", source: "Payscale 2025" },
  { value: "63%", label: "of HR leaders see employees bring inaccurate salary data", source: "Payscale 2025" },
];

// ─── Career Change Stats ────────────────────────────────────

export const CAREER_CHANGE_STATS: TStat[] = [
  { value: "53%", label: "of professionals plan to switch careers by end of 2026", source: "LinkedIn Workforce Report" },
  { value: "68%", label: "of career changers underestimate their transferable skills", source: "Career transition research" },
  { value: "6-12mo", label: "typical timeline for a well-planned career transition", source: "Career coaching data" },
];

// ─── Competitor Prices ──────────────────────────────────────

export const COMPETITOR_PRICES: TCompetitorPrice[] = [
  { name: "Jobscan", price: "$49.95", period: "/mo" },
  { name: "Teal", price: "$29", period: "/mo" },
  { name: "Resume Worded", price: "$24.99", period: "/mo" },
  { name: "FinalRound AI", price: "$149", period: "/mo" },
  { name: "Enhancv", price: "$19.99", period: "/mo" },
  { name: "Career Coach", price: "$150-300", period: "/session" },
];

// ─── Expert Quotes ──────────────────────────────────────────

export const RECRUITER_QUOTES: TExpertQuote[] = [
  {
    quote: "The initial answer doesn't determine outcomes — the FOLLOW-UP questions do. Candidates fail when their polished answers can't withstand 'tell me more' probing.",
    attribution: "Hiring professional, 38 years experience",
  },
  {
    quote: "The most memorable cover letter I ever read opened with raw, personal storytelling. Generic 'I am writing to express my interest' letters are immediately discarded.",
    attribution: "Hiring professional, 38 years experience",
  },
  {
    quote: "A resume is not a list of tasks. It's a marketing document that tells the story of your impact.",
    attribution: "Laszlo Bock",
    role: "Former SVP People Operations, Google",
  },
  {
    quote: "The illiterate of the 21st century will not be those who cannot read and write, but those who cannot learn, unlearn, and relearn.",
    attribution: "Alvin Toffler",
    role: "Futurist and author",
  },
  {
    quote: "The future belongs to those who learn more skills and combine them in creative ways.",
    attribution: "Robert Greene",
    role: "Author of Mastery",
  },
  {
    quote: "Your career is a marathon, not a sprint. Every step you take today compounds.",
    attribution: "Reid Hoffman",
    role: "LinkedIn Co-founder",
  },
];

// ─── Pain / Solution Pairs ──────────────────────────────────

export const PAIN_SOLUTIONS: TPainSolution[] = [
  {
    pain: "25% of resumes are flagged as AI-generated by recruiters. Generic tools make you blend in, not stand out.",
    solution: "We enhance YOUR voice — no 'spearheaded,' 'leveraged,' or 'synergized.' Your stories, your impact, just optimized.",
    source: "2026 Recruiter Survey",
  },
  {
    pain: "90%+ match scores on keyword tools don't translate to interviews. Keyword counting is outdated for semantic ATS.",
    solution: "Evidence-based matching that quotes your exact resume text and explains matches from a recruiter's perspective.",
    source: "2025 ATS Technology Report",
  },
  {
    pain: "43% of ATS rejections stem from formatting errors — tables, two-column layouts, embedded fonts — not qualifications.",
    solution: "Format-first optimization catches the 43% that fail before keywords even matter. We check against Greenhouse, Lever, Workday, and iCIMS.",
    source: "TopResume Study",
  },
  {
    pain: "AI mock interview tools produce 'polished but defenseless' answers. Users pass practice but fail under real follow-up probing.",
    solution: "Follow-up question preparation and defensibility coaching — what no competitor does. We prep you 2-3 layers deep.",
    source: "Interview coaching research",
  },
  {
    pain: "27% of employees say AI inflates their salary expectations. 63% of HR leaders see inaccurate data in negotiations.",
    solution: "Honest market data with source caveats. We recommend verified sources and never hallucinate salary figures.",
    source: "Payscale 2025",
  },
  {
    pain: "Career tools charge $29-$149/month for single-purpose subscriptions. Most users only need them during active job searches.",
    solution: "Pay per use with tokens — no subscription lock-in. A full resume optimization costs about $2.93. Start free with 15 tokens.",
  },
];

// ─── Convenience Selectors ──────────────────────────────────

export function getStatsByTag(tag: string): TStat[] {
  const map: Record<string, TStat[]> = {
    resume: ATS_STATS.slice(0, 3),
    ats: ATS_STATS.slice(0, 3),
    "ai-displacement": AI_DISPLACEMENT_STATS.slice(0, 3),
    displacement: AI_DISPLACEMENT_STATS.slice(0, 3),
    interview: INTERVIEW_STATS,
    salary: SALARY_STATS,
    "career-change": CAREER_CHANGE_STATS,
    linkedin: ATS_STATS.slice(3, 6),
  };
  return map[tag] ?? ATS_STATS.slice(0, 3);
}

export function getQuoteByTopic(topic: string): TExpertQuote {
  const map: Record<string, number> = {
    resume: 2,
    interview: 0,
    "cover-letter": 1,
    displacement: 3,
    career: 4,
    salary: 5,
  };
  return RECRUITER_QUOTES[map[topic] ?? 0];
}
